services:
  postgres:
    container_name: postgres
    image: pgvector/pgvector:pg17
    environment:
      - POSTGRES_DB=springai
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data
      - ./data/postgres/bak:/var/lib/postgresql/bak
      - ./config/postgres/sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  cognee_mcp:
    container_name: cognee
    image: cognee/cognee-mcp:latest
    volumes:
      - ./config/cognee/.env:/app/.env
      - ./data/cognee/docs/:/var/docs/
      - ./data/cognee/cognee_data/:/cognee_data/
    environment:
      - HOST=0.0.0.0
      - ENVIRONMENT=local
      - TRANSPORT_MODE=http
    ports:
      - "9000:8000"
    depends_on:
      postgres:
        condition: service_healthy

  neo4j:
    image: neo4j:latest
    container_name: neo4j
    user: neo4j:neo4j
    environment:
      - NEO4J_AUTH=neo4j/jjjjjjjj
      - NEO4J_dbms_security_procedures_unrestricted=gds.*,apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*,gds.*
      - NEO4J_PLUGINS=["apoc"] #graph-data-science
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      #- ./config/neo4j/config/neo4j.conf:/var/lib/neo4j/conf/neo4j.conf
      - ./data/neo4j/data:/data
      - ./data/neo4j/logs:/logs
      - ./data/neo4j/plugins:/plugins
      - ./data/neo4j/import:/import